# Generated by Django 5.0.1 on 2024-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=25, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('activo', models.IntegerField()),
            ],
        ),
    ]
