# Generated by Django 5.0.6 on 2024-07-02 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario ', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
